name: Docker
on:
  push:
    branches:
      - 'main'
      - 'metricsfilter'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: 'arm64'
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: vladikamira/promxy:${{ github.ref_name }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: 'echo ${{ steps.buildx.outputs.platforms }}'

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push -t vladikamira/promxy:${GITHUB_REF##*/} .
